kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tools
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: central-argocd
  source:
    path: definitions
    repoURL: 'https://github.com/rainerleber/argocd-apps.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      selfHeal: true