apiVersion: networking.k8s.io/v1
kind: Ingress	
metadata:	
  name: argocd	
  namespace: argocd
  annotations:
    cert-manager.io/issuer-name: letsencrypt
    cert-manager.io/issuer-kind: ClusterIssuer
spec:
  ingressClassName: cilium
  rules:
    - host: "argocd.apps.k8s.leber.com.de"
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 80
            path: /
            pathType: Prefix

