---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.5/manifests/ha/install.yaml
  - ingress.yaml
  - namespace.yaml
  - project.yaml
  - cmp-plugin.yaml
  - default-app.yml

namespace: argocd

commonLabels:
  created-by: kustomize

patchesStrategicMerge:
  - overwrites/argocd-cm.yaml
  - overwrites/argocd-server.yaml
  - overwrites/namespace-fix.yaml
  - overwrites/argocd-repo-server.yaml
  - overwrites/argocd-rbac-cm.yaml

secretGenerator:
  - name: github-tools-https-creds
    literals:
      - type=git
      - name=argocd-github-app
      - url=https://github.com
      - githubAppID=257931
      - githubAppInstallationID=30894190
    files:
      - files/githubAppPrivateKey        

  - name: argocd-vault-plugin-credentials
    literals:
      - AVP_AUTH_TYPE=approle
      - AVP_ROLE_ID=0ff15838-f746-ba90-069b-a214d39d99c3
      - AVP_SECRET_ID=5e065704-531b-0b3d-d00f-26f7525d69e0
      - AVP_TYPE=vault
      - VAULT_ADDR=https://vault.apps.k8s.leber.com.de


generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-tools-https-creds
        labels:
          argocd.argoproj.io/secret-type: repo-creds

  - target:
      kind: Role
      name: argocd-server
    patch: |-
      - op: add
        path: /rules/0/resources/-
        value: pods/exec

  # - target:
  #     kind: ServiceAccount
  #     name: argocd-dex-server
  #   patch: |-
  #     - op: add
  #       path: /metadata/annotations/serviceaccounts.openshift.io~1oauth-redirecturi.argocd
  #       value:
  #         https://argocd.apps.k8s.leber.com.de/api/dex/callback

## must be adjusted if new version
  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/env/0/value
        value: "1.13.0"

  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "quay.io/argoproj/argocd:v2.6.5"
      - op: replace
        path: /spec/template/spec/containers/1/image
        value: "quay.io/argoproj/argocd:v2.6.5"
      - op: replace
        path: /spec/template/spec/containers/2/image
        value: "quay.io/argoproj/argocd:v2.6.5"

  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-tools-https-creds
        labels:
          argocd.argoproj.io/secret-type: repo-creds

  # this patch will delete the network policy 'argocd-redis-ha-server-network-policy'
  # this patch must be reviewed from time to time
  # at the moment the policy will prevent creating redis servers
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: argocd-redis-ha-server-network-policy
      spec: ''
  # this patch will delete the network policy 'argocd-redis-ha-proxy-network-policy'
  # this patch must be reviewed from time to time
  # at the moment the policy will prevent creating redis servers
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: argocd-redis-ha-proxy-network-policy
      spec: ''
