---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.0/manifests/install.yaml
  - ingress.yaml
  - namespace.yaml
  - project.yaml
  - cmp-plugin.yaml
  - default-app.yml

namespace: argocd

commonLabels:
  created-by: kustomize

patchesStrategicMerge:
  - overwrites/argocd-cm.yaml
  - overwrites/argocd-server.yaml
  - overwrites/namespace-fix.yaml
  - overwrites/argocd-repo-server.yaml
  - overwrites/argocd-rbac-cm.yaml

secretGenerator:
  - name: github-tools-https-creds
    literals:
      - type=git
      - name=argocd-github-app
      - url=https://github.com
      - githubAppID=257931
      - githubAppInstallationID=30894190
    files:
      - files/githubAppPrivateKey        

  - name: argocd-vault-plugin-credentials
    literals:
      - AVP_AUTH_TYPE=approle
      - AVP_ROLE_ID=281c0440-2f5c-1912-79f4-af32367cdb11
      - AVP_SECRET_ID=3ac0dbfd-3869-9999-4c6c-17b6e45de30d
      - AVP_TYPE=vault
      - VAULT_ADDR=https://vault.apps.k8s.leber.com.de


generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-tools-https-creds
        labels:
          argocd.argoproj.io/secret-type: repo-creds
  - target:
      kind: ServiceAccount
      name: argocd-dex-server
    patch: |-
      - op: add
        path: /metadata/annotations/serviceaccounts.openshift.io~1oauth-redirecturi.argocd
        value:
          https://argocd.apps.k8s.leber.com.de/api/dex/callback
