---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.5/manifests/install.yaml
  - ingress.yaml
  - namespace.yaml
  - project.yaml
  - cmp-plugin.yaml
  - default-app.yml

namespace: argocd

commonLabels:
  created-by: kustomize

patchesStrategicMerge:
  - overwrites/argocd-cm.yaml
  - overwrites/argocd-server.yaml
  - overwrites/namespace-fix.yaml
  - overwrites/argocd-repo-server.yaml
  - overwrites/argocd-rbac-cm.yaml

secretGenerator:
  - name: github-tools-https-creds
    literals:
      - type=git
      - name=argocd-github-app
      - url=https://github.com
      - githubAppID=257931
      - githubAppInstallationID=30894190
    files:
      - files/githubAppPrivateKey        

  - name: argocd-vault-plugin-credentials
    literals:
      - AVP_AUTH_TYPE=approle
      - AVP_ROLE_ID=0ff15838-f746-ba90-069b-a214d39d99c3
      - AVP_SECRET_ID=5e065704-531b-0b3d-d00f-26f7525d69e0
      - AVP_TYPE=vault
      - VAULT_ADDR=http://vault.apps.k8s.leber.com.de


generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-tools-https-creds
        labels:
          argocd.argoproj.io/secret-type: repo-creds

  # - target:
  #     kind: ServiceAccount
  #     name: argocd-dex-server
  #   patch: |-
  #     - op: add
  #       path: /metadata/annotations/serviceaccounts.openshift.io~1oauth-redirecturi.argocd
  #       value:
  #         https://argocd.apps.k8s.leber.com.de/api/dex/callback
