---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: central-argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  description: Central ArgoCD
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: aks-project
#   namespace: argocd
# spec:
#   sourceRepos:
#   - '*'
#   destinations:
#   - namespace: '*'
#     server: 'https://k8s-e02eb21e.hcp.northeurope.azmk8s.io:443'
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'