{{ if ne .Values.overtake "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-kubernetes.default.svc
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: {{ .Values.hostname | b64enc }}
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
{{ end }}
