{{ if ne .Values.overtake "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
stringData:
  AWS_REGION: <path:{{ $.Values.hostname }}#secretsmanager_region>
  AWS_ACCESS_KEY_ID: <path:{{ $.Values.hostname }}#secretsmanager_access_key_id>
  AWS_SECRET_ACCESS_KEY: <path:{{ $.Values.hostname }}#secretsmanager_secret_access_key_id>
  AVP_TYPE: awssecretsmanager
{{ end }}